# Generated by Django 4.1.1 on 2022-09-13 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_channels_has_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
